Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox"

  config.vm.provision "shell", path: "bootstrap-base.sh"

  config.vm.define "adm1" do |node|
    node.vm.hostname = "adm1"
    node.vm.network "private_network", ip: "192.168.11.5"
    node.vm.provision :shell, path: "bootstrap-adm.sh"
  end

  (1..2).each do |i|
    config.vm.define "pg#{i}" do |node|
      node.vm.hostname = "pg#{i}"
      node.vm.network "private_network", ip: "192.168.11.1#{i}"
      node.vm.provision :shell, path: "bootstrap-pg.sh"
    end
  end

  (1..2).each do |i|
    config.vm.define "nginx#{i}" do |node|
      node.vm.hostname = "nginx#{i}"
      node.vm.network "private_network", ip: "192.168.11.2#{i}"
      node.vm.provision :shell, path: "bootstrap-nginx.sh"
    end
  end

  config.vm.boot_timeout  = 60

  # lxc overrides
  config.vm.provider "lxc" do |lxc|
    lxc.container_name = :machine
    lxc.customize 'cgroup.memory.limit_in_bytes', '512M'
  end

  # virtualbox overrides
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end

end
